channels:
  - conda-forge
dependencies:
  - pandas=0.25
  - pycountry
  - pip=8.1.2
  - numpy=1.16
  - matplotlib
  - nbserverproxy
  - python=2.7
  - pip:
    - wbdata==0.2.7
    - statsmodels.formula.api=0.10.1
