channels:
  - conda-forge
dependencies:
  - pandas=0.19.2
  - pycountry
  - pip=8.1.2
  - numpy=1.11.*
  - matplotlib
  - python=2.7
  - pip:
    - wbdata==0.2.7
    - statsmodels.formula.api==0.10.1
