channels:
  - conda-forge
dependencies:
  - python
  - numpy>=1.11
  - pip
  - scipy>=0.18
  - patsy>=0.4.0
  - cython>=0.24
  - pip:
    - wbdata==0.2.7
    - statsmodels.formula.api>=0.5.0
    - pandas>=0.19
    - matplotlib
